### ISSUE TITLE
Strange error on built with Qt 5.11.2 (with mingw32 5.3.0)

### ISSUE THREAD

**Issue by ivtts** [parihaaraka/sqt#2]
Hello 
I'm trying biuld sqt with Qt Creator on Windows 7 x86. I use Qt 5.11.2 (for mingw32) and mingw32 5.3.0.
Error are:
`C:\Qt\Tools\mingw530_32\i686-w64-mingw32\include\c++\thread:88: ошибка: no match for 'operator>' (operand types are 'std::thread::native_handle_type {aka ptw32_handle_t}' and 'std::thread::native_handle_type {aka ptw32_handle_t}')
       { return __x._M_thread > __y._M_thread; }
                              ^
`
Also where is more compiler note's, like this:
`C:\Qt\Tools\mingw530_32\i686-w64-mingw32\include\c++\bits\stl_pair.h:233: candidate: template<class _T1, class _T2> constexpr bool std::operator>(const std::pair<_T1, _T2>&, const std::pair<_T1, _T2>&)
     operator>(const pair<_T1, _T2>& __x, const pair<_T1, _T2>& __y)
     ^`
Any idea what could be wrong?

**Comment by parihaaraka** [comment]
Sqt uses odbc and pg api via external libraries. You have to get them built with mingw32 too, so just prefer Visual Studio on Windows.

**Comment by ivtts** [comment]
I see, thanks for the clarification. I'll try with MSVC 2015.

**Comment by ivtts** [comment]
I install Qt 5.11.2 pre-buile for msvc-2015 and install MSVC2015 Community Edition. It now compiled normally, and run successfully, thanks )

What about minimal version of PostgreSQL that supports with sqt?
