### ISSUE TITLE
Query editor not visible

### ISSUE THREAD

**Issue by ivtts** [parihaaraka/sqt#3]
Compiled with Qt 5.11.2 MSVC 2015 (32 bit).
When switch to query editor, I do not see where to enter the request.
The program looks like this - https://i.imgur.com/CmaimaF.png

**Comment by parihaaraka** [comment]
You need to create editor tab: locate cursor within opened connection scope (DB objects tree) and press Ctrl+N.

**Comment by parihaaraka** [comment]
F2 switches between db node content and editors area, not an editor. Every editor tab opens within existing db connection according to cursor position (within tree or current editor). You must open every tab explicitly.

**Comment by ivtts** [comment]
Thanks, it works. It turned out so simple )
