### ISSUE TITLE
Don't expanded object tree on some database

### ISSUE THREAD

**Issue by ivtts** [parihaaraka/sqt#4]
There is remote Postgres 9.6 on Windows XP. When i connect to him, some databases are viewed normally via object inspector, except one. When click in object inspector on this db name (NFCRW) in lower panel appears error [message](https://pastebin.com/5tZqQWXF). PgAdmin3 normally displays the objects of this database.
What minimal version of PostgreSQL server may use with this programm? It depends of linked libpq.lib version?

**Comment by parihaaraka** [comment]
Alias type `regrole` for `oid` data type was introduced in 9.5. I doubt you use 9.6. Anyway you may adjust
`scripts/postgres/content/database.sql` (and some others if needed) to support the version you want. See [scripts/README.md](https://github.com/parihaaraka/sqt/blob/master/scripts/README.md) for additional info.

**Comment by parihaaraka** [comment]
`sqt` is just a scripts runner. All of its contents is built on sql scripts (or, probably, js - the engine is looks like ready but not used yet). I wrote existing scripts to support rdbms-es i worked with (9.6-11). I'am not sure if they runnable on lower versions. There is an ability to have version-dependent script parts, so any contribution is welcomed.

**Comment by ivtts** [comment]
Ok, thanks. We will understand further.
