### ISSUE TITLE
Cannot connect to PostgreSQL database

### ISSUE THREAD

**Issue by dimgel** [parihaaraka/sqt#7]
Hi. I create new connection with string: 

    host=127.0.0.1 port=5432 dbname=mydb user=postgres password=postgres

Looks like sqt does not recognize it's PostgreSQL, tries ODBC instead and gives me error: 

    error 0, state IM002: [unixODBC][Driver Manager]Data source name not found and no default driver specified

Or am I doing something wrong? Thanks.

Also, if I don't use %user% and %pass% macros, it probably should not popup up login dialog.

**Comment by parihaaraka** [comment]
Do not use "name" field for connection string. Otherwise I would like to see screenshot

**Comment by dimgel** [comment]
There's "dbname" parameter, but no "name". Or what do you mean?

http://dimgel.me/drop/sqt/screenshot-postgres-cannot-connect.png

**Comment by parihaaraka** [comment]
![image](https://user-images.githubusercontent.com/21237670/80630403-d39b0e00-8a5c-11ea-8ab5-b12de5faa866.png)

**Comment by dimgel** [comment]
Ah, damn. :) I see. I though that large textarea was just read-only info. Everything works now, thanks. :)
